# Generated by Django 5.0.7 on 2024-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
