# Generated by Django 5.0.6 on 2024-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GycemieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_sucre', models.IntegerField()),
                ('soif_intense', models.IntegerField()),
                ('fatigue_extreme', models.IntegerField()),
                ('vision_flou', models.IntegerField()),
                ('secheresse_bouche', models.IntegerField()),
                ('perte_poid', models.IntegerField()),
                ('cicatrisation_lente', models.IntegerField()),
                ('infection_frequente', models.IntegerField()),
            ],
        ),
    ]
