# Generated by Django 5.0.6 on 2024-07-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gycemiedata',
            name='cicatrisation_lente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gycemiedata',
            name='fatigue_extreme',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gycemiedata',
            name='infection_frequente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gycemiedata',
            name='perte_poid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gycemiedata',
            name='secheresse_bouche',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gycemiedata',
            name='soif_intense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gycemiedata',
            name='taux_sucre',
            field=models.IntegerField(default=0.1),
        ),
        migrations.AlterField(
            model_name='gycemiedata',
            name='vision_flou',
            field=models.IntegerField(default=0),
        ),
    ]
