# Generated by Django 5.0.6 on 2024-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_gycemiedata_cicatrisation_lente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gycemiedata',
            name='taux_sucre',
            field=models.FloatField(default=0.1),
        ),
    ]
