# Generated by Django 5.0.7 on 2024-08-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
